
python H:\MXD_Scan\update_mxds.py -a single -n H:\MXD_Scan\xlsx\arcgis_files\mxds_updateDDD_all\Geotech_PR_GectechALLwAddCores_RS_GSN_L_a.mxd -x H:\MXD_Scan\xlsx\arcgis_files\mxds_load_all\Geotech_PR_GectechALLwAddCores_RS_GSN_L_a.mxd.xlsx -m \\anadarko.com\world\SharedData\Houston\IntlDeepW\MOZAMBIQUE\MOZGIS\arcgis_files\mxds\Geotech_PR_GectechALLwAddCores_RS_GSN_L_a.mxd > H:\MXD_Scan\xlsx\arcgis_files\update_mxds_missed.log 2>&1

python H:\MXD_Scan\update_mxds.py -a single -n H:\MXD_Scan\xlsx\arcgis_files\mxds_updateDDD_all\Ref_AF_Project_Impacted_Communities_TP_APC_EL_EA-MZ-SR0504-APC-E22-00021-01.mxd -x H:\MXD_Scan\xlsx\arcgis_files\mxds_load_all\Ref_AF_Project_Impacted_Communities_TP_APC_EL_EA-MZ-SR0504-APC-E22-00021-01.mxd.xlsx -m \\anadarko.com\world\SharedData\Houston\IntlDeepW\MOZAMBIQUE\MOZGIS\arcgis_files\mxds\Ref_AF_Project_Impacted_Communities_TP_APC_EL_EA-MZ-SR0504-APC-E22-00021-01.mxd > H:\MXD_Scan\xlsx\arcgis_files\update_mxds_missed.log 2>&1

python H:\MXD_Scan\update_mxds.py -a single -n H:\MXD_Scan\xlsx\arcgis_files\mxds_updateDDD_all\AG_Potential_areas_agric_potential_ZJ_A3.mxd -x H:\MXD_Scan\xlsx\arcgis_files\mxds_load_all\AG_Potential_areas_agric_potential_ZJ_A3.mxd.xlsx -m \\anadarko.com\world\SharedData\Houston\IntlDeepW\MOZAMBIQUE\MOZGIS\arcgis_files\mxds\AG_Potential_areas_agric_potential_ZJ_A3.mxd > H:\MXD_Scan\xlsx\arcgis_files\update_mxds_missed.log 2>&1

python H:\MXD_Scan\update_mxds.py -a single -n H:\MXD_Scan\xlsx\arcgis_files\mxds_updateDDD_all\DUAT_Comparisions.mxd -x H:\MXD_Scan\xlsx\arcgis_files\mxds_load_all\DUAT_Comparisions.mxd.xlsx -m \\anadarko.com\world\SharedData\Houston\IntlDeepW\MOZAMBIQUE\MOZGIS\arcgis_files\mxds\DUAT_Comparisions.mxd > H:\MXD_Scan\xlsx\arcgis_files\update_mxds_missed.log 2>&1

python H:\MXD_Scan\update_mxds.py -a single -n H:\MXD_Scan\xlsx\arcgis_files\mxds_updateDDD_all\Pipeline_PB_DredgeDump_Slope_BL.mxd -x H:\MXD_Scan\xlsx\arcgis_files\mxds_load_all\Pipeline_PB_DredgeDump_Slope_BL.mxd.xlsx -m \\anadarko.com\world\SharedData\Houston\IntlDeepW\MOZAMBIQUE\MOZGIS\arcgis_files\mxds\Pipeline_PB_DredgeDump_Slope_BL.mxd > H:\MXD_Scan\xlsx\arcgis_files\update_mxds_why.log 2>&1

python H:\MXD_Scan\update_mxds.py -a single -n H:\MXD_Scan\xlsx\arcgis_files\mxds_updateDDD_all\RAP_Request\CH6-1811-02_PORT_A4_1.mxd -x H:\MXD_Scan\xlsx\arcgis_files\mxds_load_all\RAP_Request\CH6-1811-02_PORT_A4_1.mxd.xlsx -m \\anadarko.com\world\SharedData\Houston\IntlDeepW\MOZAMBIQUE\MOZGIS\arcgis_files\mxds\RAP_Request\CH6-1811-02_PORT_A4_1.mxd > H:\MXD_Scan\xlsx\arcgis_files\update_mxds_why.log 2>&1
